<h2>Importing the Libraries


In [22]:
import  numpy as np # This is used for the Calculation  
import matplotlib.pyplot as plt # ploting the garph 
import pandas as pd # it's used for the Analysing the Graph and Data Sets 

<h2> Importing the Data Set 


In [12]:
dataset = pd.read_csv('Data.csv') # This read the Data from the Data CSV file 
X = dataset.iloc[:, :-1].values# This store the all the row and all the column except the last column 
Y = dataset.iloc[:, -1].values#This store the last column which you have left above 
print(X)
print(Y)


[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


<h2>Taking care of missing data 

In [23]:
from sklearn.impute import SimpleImputer #Use of Simple Imputer is to Handle the missing Value like NaN 
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')# Missing _value = np.nan tells that which type of value you have to remove it 
imputer.fit(X[: , 1:3]) #imputer will use this value to calculate the Mean value and use it to replace it 
X[: , 1:3] = imputer.transform(X[: , 1:3]) # this line will replace the missing value and it will again transform it . 
print(X)
            


[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


<h2>Encoding the Independent Variable 

In [29]:
from sklearn.compose import ColumnTransformer # Helpful in Dealing with the Column transformation and applyying operation on the selective column 
from sklearn.preprocessing import OneHotEncoder # ( Red , Green , Blue ) ----- > ( 0 , 1 , 2 ) which is useful in the ML algorithm 
ct = ColumnTransformer( transformers = [('encoder' , OneHotEncoder() , [0])] , remainder = 'passthrough') # you are applying OneHotEncoder here on the first column after that you can leave all the rest column unchanged that's what is going  in this part 
X = np.array(ct.fit_transform(X))#The resulting X will be a NumPy array with the first column converted into multiple one-hot encoded columns.
print(X)


[[1.0 0.0 1.0 0.0 0.0 44.0 72000.0]
 [0.0 1.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 1.0 0.0 0.0 35.0 58000.0]
 [0.0 1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 1.0 0.0 0.0 37.0 67000.0]]


<h2>Encoding the Dependent variable

In [30]:
from sklearn.preprocessing import LabelEncoder # Convert the Categorical Value into the Numerical Value which we are looog forward 
le = LabelEncoder() # we have created the class for the LabelEncoder and assign with le 
y = le.fit_transform(y)# it convert your value into the Numerical value 
print(y)



[0 1 0 0 1 1 0 1 0 1]


<h2> Splitting the Dataset into the Train and Testing dataset 

In [31]:
from sklearn.model_selection import train_test_split # use to split our data 
X_train , X_test , y_train , y_test = train_test_split ( X , y , test_size = 0.2 , random_state = 1 ) # you have given the Input , output and ratio in which your data should be divided that's how the things goes 
print(X_train)
print(X_test ) 
print(y_train)
print(y_test)

[[0.0 1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 1.0 0.0 0.0 44.0 72000.0]
 [0.0 1.0 0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 1.0 0.0 0.0 35.0 58000.0]]
[[0.0 1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 1.0 0.0 0.0 37.0 67000.0]]
[0 1 0 0 1 1 0 1]
[0 1]


<h2>Feature Scaling 

In [33]:
from sklearn.preprocessing import StandardScaler #feature scaling uses
sc = StandardScaler()
X_train = sc.fit_transform(X_train)#here fit made  the mean  = 0 and the standard deviation == 1  and the other one calculate for the scaling purpose 
X_test = sc.transform(X_test)#this will ensure that the data should be on same scale as for the Train and testing data set 
print(X_test)
print(X_train)

[[-0.77459667  0.77459667 -0.77459667  1.73205081 -0.77459667 -1.46618179
  -0.9069571 ]
 [ 1.29099445 -1.29099445  1.29099445 -0.57735027 -0.77459667 -0.44973664
   0.20564034]]
[[-0.77459667  0.77459667 -0.77459667 -0.57735027  1.29099445 -0.19159184
  -1.07812594]
 [-0.77459667  0.77459667 -0.77459667  1.73205081 -0.77459667 -0.01411729
  -0.07013168]
 [ 1.29099445 -1.29099445  1.29099445 -0.57735027 -0.77459667  0.56670851
   0.63356243]
 [-0.77459667  0.77459667 -0.77459667 -0.57735027  1.29099445 -0.30453019
  -0.30786617]
 [-0.77459667  0.77459667 -0.77459667 -0.57735027  1.29099445 -1.90180114
  -1.42046362]
 [ 1.29099445 -1.29099445  1.29099445 -0.57735027 -0.77459667  1.14753431
   1.23265336]
 [-0.77459667  0.77459667 -0.77459667  1.73205081 -0.77459667  1.43794721
   1.57499104]
 [ 1.29099445 -1.29099445  1.29099445 -0.57735027 -0.77459667 -0.74014954
  -0.56461943]]
